### ISSUE TITLE
Every Player Crash when audio is play and than server restart

### ISSUE THREAD

**Issue by louis1706** [Edren-Baton-Team/AudioPlayer#15]

**Comment by Rysik5318** [comment]
![image](https://github.com/Edren-Baton-Team/AudioPlayer/assets/72207886/a38e9c3f-9ded-4f70-a6f5-7f6379c2c103)

**Comment by louis1706** [comment]
> ![image](https://github.com/Edren-Baton-Team/AudioPlayer/assets/72207886/a38e9c3f-9ded-4f70-a6f5-7f6379c2c103)
> 

You don't just need to stop all audio?

**Comment by Rysik5318** [comment]
> > ![image](https://user-images.githubusercontent.com/72207886/272387460-a38e9c3f-9ded-4f70-a6f5-7f6379c2c103.png)
> 
> You don't just need to stop all audio?

I've never had bugs like this before. I don't know.

**Comment by louis1706** [comment]
> > > ![image](https://user-images.githubusercontent.com/72207886/272387460-a38e9c3f-9ded-4f70-a6f5-7f6379c2c103.png)
> > 
> > You don't just need to stop all audio?
> 
> I've never had bugs like this before. I don't know.

Haven't you reproduced it ?

**Comment by Rysik5318** [comment]
Fixed
