### ISSUE TITLE
Two bugs in one

### ISSUE THREAD

**Issue by xplorersploder** [Edren-Baton-Team/AudioPlayer#7]
If a bot is playing music when the round ends, the server generates a new map, but it doesn't wait for players, instead delaying all incoming connections by 5 seconds forever until the owner restarts the server. This happens with any type of audio, and works worst with round end special events that extend past the server's wait time to round restart.

Could potentially be fixed by forcing the bot to stop a second before the round restarts?

The warhead stop event does not trigger when the facility explodes, only when the warhead is stopped through RA or through the warhead room in HCZ. Making us have to manually stop the music through RA, and warhead stop sounds do not work as far as I've tested.

**Comment by Rysik5318** [comment]
To be corrected
