### ISSUE TITLE
player_died_target_clip and player_died_killer_clip both play their sounds 6 times

### ISSUE THREAD

**Issue by xplorersploder** [Edren-Baton-Team/AudioPlayer#9]
Why 6 times? It's so oddly specific. It should only play once, right?
[Evidence 1](https://cdn.discordapp.com/attachments/1122038444143677451/1122839026878132384/2023-06-26_06-39-35.mp4)
[Evidence 2](https://cdn.discordapp.com/attachments/1122038444143677451/1122839027532435487/2023-06-26_06-39-15.mp4)

**Comment by xplorersploder** [comment]
On further testing, it seems it plays the event 6 times, not just a single sound. Can be seen if you use multiple different sounds

**Comment by Rysik5318** [comment]
Fixed in v2.1.4
